name: maclauncher_workspace
publish_to: none

environment:
  sdk: ^3.13.0

workspace:
  - packages/maclauncher_sdk
  - packages/launcher_core
  - example/minimal_app
  - launcher

dev_dependencies:
  lints: 6.1.0
  test: ^1.25.0
